version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: erp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - erp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  authentication-service:
    build: ./authentication-service
    container_name: erp_backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SERVER_PORT: 8080
      JWT_SECRET: "super-secret-key"
    ports:
      - "8080:8080"
    networks:
      - erp-network
    healthcheck:
         test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 0"]
         interval: 30s
         timeout: 10s
         retries: 5
         start_period: 30s

  hr-service:
    build: ./hr-service
    container_name: erp_hr_service
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SERVER_PORT: 8081
      JWT_SECRET: "super-secret-key"
    ports:
      - "8081:8081"
    networks:
      - erp-network
    healthcheck:
       test: ["CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1"]
       interval: 30s
       timeout: 10s
       retries: 5
       start_period: 30s
  finance-service:
    build: ./finance-service
    container_name: erp_finance_service
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SERVER_PORT: 8082
      JWT_SECRET: "super-secret-key"
    ports:
      - "8082:8082"
    networks:
      - erp-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8082/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  frontend:
    build: ./frontend
    container_name: erp_frontend
    restart: unless-stopped
    depends_on:
      authentication-service:
        condition: service_healthy
    environment:
      API_URL: http://authentication-service:8080
    ports:
      - "80:80"
    networks:
      - erp-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5

volumes:
  pg_data:

networks:
  erp-network:
    driver: bridge
