version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: erp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - erp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    image: aliashmawy/authentication-service:latest
    container_name: erp_backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - erp-network
    healthcheck:
        test: ["CMD", "sh", "-c", "curl -f http://localhost:8080 || exit 0"]
        interval: 30s
        timeout: 10s
        retries: 3


  frontend:
    image: aliashmawy/frontend:latest
    container_name: erp_frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    environment:
      API_URL: http://backend:8080
    ports:
      - "80:80"
    networks:
      - erp-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5


  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    networks:
      - erp-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  doc-processing:
    image: aliashmawy/doc-processing:50
    container_name: doc-processing-app
    restart: unless-stopped
    ports:
      - "7860:7860"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/invoice_reader_db
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    networks:
      - erp-network
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7860/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s


  chatbot:
    image: aliashmawy/chatbot:29
    container_name: chatbot-app
    restart: unless-stopped
    ports:
      - "7870:7860"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/invoice_reader_db
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    networks:
      - erp-network
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7860/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  hr-attrition:
    image: aliashmawy/hr-attrition:latest
    container_name: hr-attrition-app
    restart: unless-stopped
    ports:
      - "7880:7860"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    networks:
      - erp-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7860/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  tft-forecast:
    image: aliashmawy/tft-revenue-forecast:latest
    container_name: tft-forecast-app
    restart: unless-stopped
    ports:
      - "7890:7860"
    networks:
      - erp-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7860/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  prophet-forecast:
    image: aliashmawy/prophet-forecast:latest
    container_name: prophet-forecast-app
    restart: unless-stopped
    ports:
      - "7900:7860"
    networks:
      - doc-processing-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7860/docs || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  mongodb-data:
    driver: local
  mongodb-config:
    driver: local
  pg_data:
    driver: local

networks:
  erp-network:
    driver: bridge