name: Backend CI/CD

on:
  push:
    branches: [ "dev"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
     run:
          working-directory: Authentication-service


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package -DskipTests=true

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "Authentication-service"
          path: "Authentication-service"
          format: "HTML"
          out: "Authentication-service/reports"
          args: >
             --enableExperimental



      - name: Run SonarQube Scan
        run: mvn sonar:sonar \
          -Dsonar.projectKey=auth-service \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.sources=src/main/java

      - name: Check SonarQube Quality Gate
        id: qualitygate
        uses: SonarSource/sonarqube-quality-gate-action@master
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-host-url: ${{ secrets.SONAR_HOST_URL  }}

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        with:
          run: detect --source . --report-format json --report-path Authentication-service/reports/gitleaks.json
