name: Backend CI/CD

on:
  push:
    branches: [ "dev"]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
 
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: gp
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d gp"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Verify Java
        run: java -version

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('Authentication-service/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        working-directory: Authentication-service
        run: mvn clean package -DskipTests=false


      - name: Run GitLeaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
          GITLEAKS_NOTIFY_USER_LIST: ${{ secrets.GITLEAKS_NOTIFY_USER_LIST }}
          GITLEAKS_SCAN_PATH: "Authentication-service"
          
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
         java-version: '21'
         distribution: 'temurin'


      # OWASP Dependency Check (SCA)
      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "auth-service"
          path: "Authentication-service"
          format: "HTML"
          out: "dependency-check-report"
      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report

      # SonarQube Scan (SAST)
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=auth-service
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.java.binaries=target

      #  Quality Gate Check
      - name: SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      #  Build Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/auth-service:${{ github.sha }} .

      # Run Temporary Container
      - name: Run Temporary Container
        run: |
          docker run -d -p 8080:8080 --name temp-container ${{ secrets.DOCKER_HUB_USERNAME }}/auth-service:${{ github.sha }}
          sleep 20
          docker ps

      # OWASP ZAP Scan (DAST)
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: "http://localhost:8080"
          docker_name: "owasp/zap2docker-stable"

      # Push Docker Image to DockerHub
      - name: Log in to DockerHub
        if: success()
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push image to DockerHub
        if: success()
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/auth-service:${{ github.sha }}