name: Backend CI/CD

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean verify -DskipTests=false

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "Authentication-service"
          path: "Authentication-service"
          format: "HTML"
          out: "Authentication-service/reports"

      - name: Run SonarQube Scan
        run: mvn sonar:sonar \
          -Dsonar.projectKey=auth-service \
          -Dsonar.host.url=${{ secrets.SONAR_HOST }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.sources=src/main/java

      - name: Check SonarQube Quality Gate
        id: qualitygate
        uses: SonarSource/sonarqube-quality-gate-action@master
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-host-url: ${{ secrets.SONAR_HOST }}

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        with:
          run: detect --source . --report-format json --report-path Authentication-service/reports/gitleaks.json

      - name: Build Docker image
        run: docker build -t auth-service:latest Authentication-service/

      
      - name: Run Auth Service
        run: docker run -d --name auth-test -p 8080:8080 auth-service:latest && sleep 10

      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:8080'
          format: html
          output: 'Authentication-service/reports/zap-report.html'
          cmd_options: '-a'

      - name: Stop Auth Service
        if: always()
        run: docker stop auth-test || true

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: Authentication-service/reports/
