name: doc-processing CI

on:
  push:
    branches: [ai-team-work]

    paths:
      - 'doc-processing/**'
      - '.github/workflows/doc-processing.yaml'
  pull_request:
    branches: [main]

  workflow_dispatch:
env:
  SERVICE_NAME: doc-processing

jobs:

  gitleaks:
    name: Secret Detection (GitLeaks)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run GitLeaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
          GITLEAKS_NOTIFY_USER_LIST: ${{ secrets.GITLEAKS_NOTIFY_USER_LIST }}
          GITLEAKS_SCAN_PATH: "${{ env.SERVICE_NAME }}"

  sonarqube:
    name: Inspect - SAST
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarQube Scan (SAST)
        continue-on-error: true
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: ${{ env.SERVICE_NAME }}
          args: >
            -Dsonar.projectKey=${{ env.SERVICE_NAME }}
            -Dsonar.sources=.
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
            -Dsonar.verbose=true

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   
        timeout-minutes: 5
        with:
          scanMetadataReportFile: "${{ env.SERVICE_NAME }}/.scannerwork/report-task.txt"

  depchecktest:
    runs-on: ubuntu-latest
    name: dependency_check_scan
    
    permissions:
      contents: read
      security-events: write 
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Dependency-Check database
        uses: actions/cache@v4
        with:
          path: ~/.dependency-check
          key: depcheck-data-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            depcheck-data-${{ runner.os }}-


      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        continue-on-error: true
        id: Depcheck
        with:
          project: '${{ env.SERVICE_NAME }}'
          path: './${{ env.SERVICE_NAME }}'
          format: 'ALL'
          out: 'reports'
          args: >
            --failOnCVSS 8
            --enableRetired
            --enableExperimental
      
      - name: Upload Dependency-Check report
        if: always()
        uses: actions/upload-artifact@v4
        with:
           name: dependency-check-report
           path: ${{ github.workspace }}/reports

      
      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: reports/dependency-check-report.sarif


  build-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    needs: [gitleaks,sonarqube,depchecktest]
    continue-on-error: true
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
        env:
          UV_PYTHON: '3.10'

      - name: Sync Dependencies
        working-directory: ./${{ env.SERVICE_NAME }}
        run: uv lock

      - name: Build Docker image
        run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} ./${{ env.SERVICE_NAME }}
    
      # - name: Run Trivy vulnerability scanner
      #   uses: aquasecurity/trivy-action@0.28.0
      #   with:
      #     image-ref: '${{ vars.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}'
      #     format: 'sarif'
      #     output: 'trivy-${{ env.SERVICE_NAME }}-results.sarif'
      #     exit-code: '1'
      #     ignore-unfixed: true
      #     vuln-type: 'os,library'
      #     severity: 'CRITICAL,HIGH'

      # - name: Upload SARIF
      #   if: always()
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: 'trivy-${{ env.SERVICE_NAME }}-results.sarif'
      #     category: trivy-python

      # - name: Generate SBOM
      #   uses: aquasecurity/trivy-action@0.18.0
      #   if: always()
      #   with:
      #     image-ref: ${{ vars.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
      #     format: 'spdx-json'
      #     output: 'sbom-${{ env.SERVICE_NAME }}.spdx.json'

      # - name: Upload SBOM
      #   uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: sbom-${{ env.SERVICE_NAME }}
      #     path: sbom-${{ env.SERVICE_NAME }}.spdx.json
      #    retention-days: 90

      - name: Log in to DockerHub
        if: always()
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push image to DockerHub
        if: always()
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: [build-scan]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make deploy script executable
        run: chmod +x scripts/deploy.sh

      - name: Deploy to EC2
        env:
          SERVICE_NAME: ${{ env.SERVICE_NAME }}
          GITHUB_SHA: ${{ github.sha }}
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

        run: scripts/deploy.sh

  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://${{ secrets.EC2_HOST }}:7860'
          cmd_options: '-a'
          allow_issue_writing: false

      - name: debug zap files
        run: ls -la .zap/
      
      - name: Upload ZAP Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
           name: zap-report
           path: .zap/*.html
        