name: Doc-Processing CI

on:
  push:
    branches: [ai-team-work]

    paths:
      - 'AI/automated_document_processing/*'
      - '.github/workflows/doc-processing.yaml'
    #   - 'AI/automated_document_processing/requirements.txt'
  pull_request:
    branches: [main]

  workflow_dispatch: 

jobs:

  gitleaks:
    name: Secret Detection (GitLeaks)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run GitLeaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
          GITLEAKS_NOTIFY_USER_LIST: ${{ secrets.GITLEAKS_NOTIFY_USER_LIST }}
          GITLEAKS_SCAN_PATH: "AI/automated_document_processing"

  sonarqube:
    name: Inspect - SAST
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarQube Scan (SAST)
        continue-on-error: true
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: AI/automated_document_processing
          args: >
            -Dsonar.projectKey=doc-processing
            -Dsonar.sources=.
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
            -Dsonar.verbose=true

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   
        timeout-minutes: 5
        with:
          scanMetadataReportFile: "AI/automated_document_processing/.scannerwork/report-task.txt"

  depchecktest:
    runs-on: ubuntu-latest
    name: dependency_check_scan
    
    permissions:
      contents: read
      security-events: write 
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Dependency-Check database
        uses: actions/cache@v4
        with:
          path: ~/.dependency-check
          key: depcheck-data-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            depcheck-data-${{ runner.os }}-


      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'AI-automated_document_processing'
          path: './AI/automated_document_processing'
          format: 'ALL'
          out: 'reports'
          args: >
            --failOnCVSS 7
            --enableRetired
            --enableExperimental
      
      - name: Upload Dependency-Check report
        if: always()
        uses: actions/upload-artifact@v4
        with:
           name: dependency-check-report
           path: ${{ github.workspace }}/reports

      
      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: reports/dependency-check-report.sarif


  build-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    #needs: [gitleaks,sonarqube,depchecktest]
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/doc-processing:${{ github.sha }} ./AI/automated_document_processing

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ vars.DOCKERHUB_USERNAME }}/doc-processing:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-doc-processing-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-doc-processing-results.sarif'
          category: trivy-python

      - name: Generate SBOM
        uses: aquasecurity/trivy-action@0.18.0
        if: always()
        with:
          image-ref: ${{ vars.DOCKERHUB_USERNAME }}/doc-processing:${{ github.sha }}
          format: 'spdx-json'
          output: 'sbom-doc-processing.spdx.json'

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: sbom-doc-processing
          path: sbom-doc-processing.spdx.json
          retention-days: 90

      

      - name: Log in to DockerHub
        if: success()
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push image to DockerHub
        if: success()
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/doc-processing:${{ github.sha }}