name: Frontend CI (Angular)

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Frontend  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build

      - name: Install SonarScanner
        run: |
              sudo apt-get update
              sudo apt-get install openjdk-17-jre -y
              wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
              unzip sonar-scanner-cli-5.0.1.3006-linux.zip
              sudo mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
              echo "/opt/sonar-scanner/bin" >> $GITHUB_PATH
      - name: Check SonarQube Connection
        run: |
           curl -f ${{ secrets.SONAR_HOST_URL }}/api/system/status || exit 1


      # üß™ SonarQube Scan (Static Analysis)
      #  SonarQube Scan (SAST)
      # - Runs only if SONAR_HOST_URL secret exists (so pipeline doesn‚Äôt fail now)
      - name: SonarQube Scan
        env:
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
              if [ -z "$SONAR_HOST_URL" ]; then
               echo "‚ö†Ô∏è SonarQube skipped - missing SONAR_HOST_URL secret"
               else
               sonar-scanner \
              -Dsonar.projectKey=erp-frontend \
              -Dsonar.sources=. \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.login=$SONAR_TOKEN
              fi


      #  Build Docker Image
      - name: Build Docker image
        run: docker build -t erp-frontend:latest .
        working-directory: Frontend

      # Trivy Security Scan (SCA)
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'erp-frontend:latest'
          format: 'table'
          exit-code: '0'