name: Frontend CI/CD (Angular + Security + Quality Gates)

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Frontend

    steps:
      # Checkout the Code
      # - Always the first step
      - name: Checkout code
        uses: actions/checkout@v4

      # Secret Detection — Gitleaks
      # - Scans for leaked credentials or API keys
      - name: Run Gitleaks (Secret Scan)
        uses: zricethezav/gitleaks-action@v2
        env:
         GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        with:
         args: detect --source . --report-format json --report-path gitleaks-report.json



      # Setup Node.js for Angular Build
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install Frontend Dependencies
      - name: Install dependencies
        run: npm install

      # Build Angular App
      - name: Build Angular App
        run: npm run build

      #  Install SonarScanner (Static Code Analysis)
      # - Used for Quality Gates + Code Smells + Security Hotspots
      # ⚡ Add Cache for SonarScanner binaries to speed up installation
      - name: Cache SonarScanner binary
        id: sonar-bin-cache
        uses: actions/cache@v3
        with:
          path: /opt/sonar-scanner
          key: sonar-binary-${{ runner.os }}-v3

      - name: Install SonarScanner
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install openjdk-17-jre -y
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip
          sudo mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
          echo "/opt/sonar-scanner/bin" >> $GITHUB_PATH


      # Check SonarQube Connection
      - name: Check SonarQube Connection
        run: |
          curl -f ${{ secrets.SONAR_HOST_URL }}/api/system/status || exit 1

      # Cache SonarQube Plugins and Rules
      # - Prevents re-downloading every run → saves time
      - name: Cache SonarQube files
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: sonar-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-v3

      - name: Clean possible corrupted sonar cache
        run: |
            echo "Removing any old Sonar temp files..."
            rm -rf /opt/sonar-scanner/.sonar/_tmp || true
            rm -rf ~/.sonar/cache/_tmp || true
  

      # SonarQube Analysis (Static App Security Testing)
      - name: SonarQube Scan (SAST)
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: Frontend
          args: >
            -Dsonar.projectKey=erp-frontend
            -Dsonar.sources=src
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # SonarQube Quality Gate Check
      # - Stops the pipeline if code quality doesn't meet the gate
      - name: SonarQube Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
         scanMetadataReportFile: Frontend/.scannerwork/report-task.txt
         pollingTimeoutSec: 300


      # OWASP Dependency Check
      # - Detects vulnerable libraries in Angular project
      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'Frontend'
          path: '.'
          format: 'HTML'

      # Build Docker Image
      - name: Build Docker image
        run: docker build -t erp-frontend:latest .
        working-directory: Frontend
        # Run frontend container
      - name: Run frontend container
        run: docker run -d -p 8080:80 --name erp-frontend-container erp-frontend:latest

      # Trivy Security Scan (SCA)
      # Scans Docker image for known vulnerabilities (CVEs)
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'erp-frontend:latest'
          format: 'table'
          exit-code: '0'


      # OWASP ZAP Baseline Scan (DAST)
      # Dynamic scan simulating real-world attacks
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: ${{ secrets.APP_URL }}
          cmd_options: '-t 5m -I'

      # Upload Reports as Artifacts
      # Store reports (Sonar, ZAP, Trivy, Gitleaks, etc.)
      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: frontend-security-reports
          path: |
            gitleaks-report.json
            dependency-check-report.html


      # Notify Team on Slack (Optional)
      #  Sends build summary to Slack channel (if webhook configured)
     
     
        