name: Frontend CI/CD (Angular + Security + Quality Gates)

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Frontend

    steps:
      # Checkout the Code
      # - Always the first step
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Secret Detection â€” Gitleaks
      # - Scans for leaked credentials or API keys
      - name: Run Gitleaks (Secret Scan)
        uses: zricethezav/gitleaks-action@v2
        env:
         GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        with:
         run: detect --source . --report-format json --report-path gitleaks-report.json



      # Setup Node.js for Angular Build
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install Frontend Dependencies
      - name: Install dependencies
        run: npm install

      # Build Angular App
      - name: Build Angular App
        run: npm run build

      #  Install SonarScanner (Static Code Analysis)
      # - Used for Quality Gates + Code Smells + Security Hotspots
      # âš¡ Add Cache for SonarScanner binaries to speed up installation
      - name: Cache SonarScanner binary
        id: sonar-bin-cache
        uses: actions/cache@v3
        with:
          path: /opt/sonar-scanner
          key: sonar-binary-${{ runner.os }}-v5

      - name: Install SonarScanner
        if: steps.sonar-bin-cache.outputs.cache-hit != 'true'

        run: |
          sudo apt-get update
          sudo apt-get install openjdk-17-jre -y
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip
          sudo mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
          echo "/opt/sonar-scanner/bin" >> $GITHUB_PATH


      

      # Check SonarQube Connection
      - name: Check SonarQube Connection
        run: |
          curl -f ${{ secrets.SONAR_HOST_URL }}/api/system/status || exit 1
      
            # Cache SonarQube Plugins and Rules
      # - Prevents re-downloading every run â†’ saves time
      - name: Cache SonarQube files
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: sonar-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-v4
  

      # SonarQube Analysis (Static App Security Testing)
      - name: SonarQube Scan (SAST)
        continue-on-error: true
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: Frontend
          args: >
            -Dsonar.projectKey=erp-frontend
            -Dsonar.sources=src
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}


      # SonarQube Quality Gate Check
      # - Stops the pipeline if code quality doesn't meet the gate
      - name: SonarQube Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        continue-on-error: true
        env:
         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
         scanMetadataReportFile: Frontend/.scannerwork/report-task.txt
         pollingTimeoutSec: 300


      # OWASP Dependency Check
      # - Detects vulnerable libraries in Angular project
      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'Frontend'
          path: '.'
          format: 'HTML'

      # Build Docker Image
      - name: Build Docker image
        run: docker build -t erp-frontend:latest .
        working-directory: Frontend

      - name: Create Docker network
        run: docker network create erp-network || true

        # Run frontend container
      - name: Run frontend container
        run: docker run -d --network erp-network -p 8080:80 --name erp-frontend-container erp-frontend:latest

      #  Verify the container is running and reachable
      - name: Verify Docker container is running
        run: |
          echo " Checking running containers..."
          docker ps
          echo " Testing if frontend is reachable..."
          sleep 5
          curl -v http://localhost:8080 || (echo " App not reachable on port 8080" && exit 1)

      # Trivy Security Scan (SCA)
      # Scans Docker image for known vulnerabilities (CVEs)
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'erp-frontend:latest'
          format: 'table'
          exit-code: '0'


            # OWASP ZAP Baseline Scan 
      - name: Run OWASP ZAP Baseline Scan (manual)
        run: |
          echo "ðŸš€ Running OWASP ZAP Baseline Scan..."
          docker pull ghcr.io/zaproxy/zaproxy:stable
          docker run -v $(pwd):/zap/wrk/:rw \
            --network=erp-network \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://erp-frontend-container:80 \
            -J report_json.json \
            -w report_md.md \
            -r report_html.html \
            -m 5 -I

      # Upload Reports as Artifacts
      # Store reports (Sonar, ZAP, Trivy, Gitleaks, etc.)
      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: frontend-security-reports
          path: |
            gitleaks-report.json
            dependency-check-report.html

           # Send Report via Email
      - name: Send report via email
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Frontend Security & Code Quality Report - ${{ github.ref_name }}"
          to: "beshooseha71@gmail.com "
          from: "Konecta CI/CD <${{ secrets.EMAIL_USERNAME }}>"
          body: |
            Hi team ðŸ‘‹,
            The CI/CD pipeline has completed successfully.
            Attached are the latest code analysis reports (SonarQube, Trivy, ZAP, etc).
          attachments: |
            Frontend/gitleaks-report.json
            Frontend/dependency-check-report.html
            Frontend/report_html.html

