name: Frontend CI (Angular)

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Frontend  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build

      - name: Install SonarScanner
        run: |
              sudo apt-get update
              sudo apt-get install openjdk-17-jre -y
              wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
              unzip sonar-scanner-cli-5.0.1.3006-linux.zip
              sudo mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
              echo "/opt/sonar-scanner/bin" >> $GITHUB_PATH
      - name: Check SonarQube Connection
        run: |
           curl -f ${{ secrets.SONAR_HOST_URL }}/api/system/status || exit 1

      # ðŸ§  Cache SonarQube Scanner + Plugins
      - name: Cache SonarQube files
        uses: actions/cache@v3
        with:
         path: ~/.sonar/cache
         key: sonar-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}


      # ðŸ§ª SonarQube Scan (Static Analysis)
      #  SonarQube Scan (SAST)
      # - Runs only if SONAR_HOST_URL secret exists (so pipeline doesnâ€™t fail now)
      

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: Frontend
        
          args: "-Dsonar.projectKey=erp-frontend -Dsonar.sources=. -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} -Dsonar.login=${{ secrets.SONAR_TOKEN }}"
      
          #  Build Docker Image
      - name: Build Docker image
        run: docker build -t erp-frontend:latest .
        working-directory: Frontend

      # Trivy Security Scan (SCA)
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'erp-frontend:latest'
          format: 'table'
          exit-code: '0'

            # ðŸ“¨ Send Report via Email
      - name: Send Email Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}        
          to: aliashmawy595@gmail.com
          subject: "Frontend CI Report"
          body: |
            Hello Team,
            
            The latest CI run for Angular Frontend (branch: ${{ github.ref_name }}) has completed.
            
            âœ… Build Completed
            âœ… SonarQube Scan Completed
            âœ… Docker Image Built
            âœ… Trivy Scan Completed
            
            Check the workflow run here: ${{ github.run_url }}
         
