name: Frontend CI/CD

on:
  push:
    branches: ["dev"]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: ["main"]
  workflow_dispatch:
env:
  SERVICE_NAME: frontend

jobs:

  gitleaks:
    name: Secret Detection (GitLeaks)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run GitLeaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
          GITLEAKS_SCAN_PATH: "${{ env.SERVICE_NAME }}"


  sonarqube:
    name: Inspect - SAST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: ./${{ env.SERVICE_NAME }}

      - name: Build Angular App
        run: npm run build
        working-directory: ./${{ env.SERVICE_NAME }}

      - name: Cache SonarQube files
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: sonar-${{ runner.os }}-${{ hashFiles('${{ env.SERVICE_NAME }}/package-lock.json') }}

      - name: SonarQube Scan (SAST)
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: ${{ env.SERVICE_NAME }}
          args: >
            -Dsonar.projectKey=${{ env.SERVICE_NAME }}
            -Dsonar.sources=.
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: SonarQube Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        continue-on-error: true
        with:
          scanMetadataReportFile: ${{ env.SERVICE_NAME }}/.scannerwork/report-task.txt
          pollingTimeoutSec: 300
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  depcheck:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: '${{ env.SERVICE_NAME }}'
          path: './${{ env.SERVICE_NAME }}'
          format: 'ALL'
          out: '${{ env.SERVICE_NAME }}/reports'

  build-scan:
    name: Build Docker & Security Scan
    runs-on: ubuntu-latest
    needs: [gitleaks, sonarqube, depcheck]
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ github.run_number }} ./${{ env.SERVICE_NAME }}

      - name: Create Docker network
        run: docker network create erp-network || true

      - name: Run frontend container
        run: docker run -d --network erp-network -p 8080:80 --name erp-frontend-container ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ github.run_number }}

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ github.run_number }}

      - name: Create reports folder
        run: mkdir -p ${{ env.SERVICE_NAME }}/reports

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ github.run_number }}
          format: 'json'
          exit-code: '0'
          output: "${{ env.SERVICE_NAME }}/reports/trivy_report.json"

      - name: Generate SBOM
        uses: aquasecurity/trivy-action@0.18.0
        with:
          image-ref: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ github.run_number }}
          format: 'spdx-json'
          output: 'sbom-${{ env.SERVICE_NAME }}.spdx.json'

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: frontend-security-reports
          path: |
            ${{ env.SERVICE_NAME }}/reports/trivy_report.json
            ${{ env.SERVICE_NAME }}/reports/dependency-check-report.html
            ${{ env.SERVICE_NAME }}/gitleaks-report.json
            sbom-${{ env.SERVICE_NAME }}.spdx.json



  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: [build-scan]
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Change image tag and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin ${{ github.ref_name }}
          sed -i "s|${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SERVICE_NAME }}:.*|${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{github.run_number}}|g" docker-compose.yml
          git add docker-compose.yml
          git commit -m "Update authentication-service tag to 162 in docker-compose.yml" || echo "No changes to commit"
          git push || echo "Nothing to push"
 
      - name: Make deploy script executable
        run: chmod +x scripts/deploy.sh

      - name: Deploy new app version
        env:
          SERVICE_NAME: ${{ env.SERVICE_NAME }}
          github_run_number: ${{ github.run_number }}
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          DOCKER_HUB_USERNAME: ${{secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          REPO_URL: https://github.com/${{ github.repository }}
          BRANCH: ${{ github.ref_name }}


        run: scripts/deploy.sh

  zap_scan:
    runs-on: ubuntu-latest
    needs: [deploy]
    name: Scan with ZAP
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://${{ secrets.EC2_HOST }}:${{ env.SERVICE_PORT }}'
          artifact_name: 'zap-report'
          cmd_options: '-a'
          allow_issue_writing: false